# Generated by Django 4.0.4 on 2022-05-28 05:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import todos.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=1000)),
                ('due_date', models.DateField(validators=[todos.models.validate_date])),
                ('tag', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('open', 'OPEN'), ('working', 'WORKING'), ('done', 'DONE'), ('overdue', 'OVERDUE')], default='open', max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['status'],
            },
        ),
    ]
